name: Run MIPS Program

on:
  push:
    branches:
      - main

jobs:
  run-mips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run MARS
        run: |
          java -jar Mars4_5.jar nc main.asm
